name: "Spelling Mistake"
description: "Fill out this form, so I can fix my mistake"
title: "Spelling: "
labels: "spelling"
assignees: kurtschambach
body:
  - type: markdown
    attributes:
      value: "**Thanks for taking the time to fill out this issue!**"
  - type: textarea
    attributes:
      label: The misspelled word
      placeholder: e.g. "helpfull"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Correct spelling (optional)
      placeholder: e.g. "helpful"
    validations:
      required: false
